In [1]:
import cv2
img = cv2.imread('../sample_image/prod.png')
type(img)

numpy.ndarray

In [2]:
img.ndim

3

In [3]:
img.shape

(512, 509, 3)

In [4]:
img.size #512*509*3

781824

In [5]:
#이미지 픽셀 데이터는 음수이거나 소수점 없음
#값의 최대 크기 255이므로 부호없는 8비트 이므로 uint8 데이터 타입으로 사용
img.dtype 

dtype('uint8')

In [6]:
# 1바이트
img.itemsize 

1

In [11]:
import numpy as np

a = np.array([1,2,3,4])
print(a.dtype)
print(a.shape)

int64
(4,)


In [16]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [19]:
c = np.array([1,2,3.14,4])
print(c)
print(c.dtype)

[1.   2.   3.14 4.  ]
float64


In [23]:
d = np.array([1,2,3,4], dtype=np.float32)
d

array([1., 2., 3., 4.], dtype=float32)